openapi: 3.0.0
info:
  description: |-
    A basic API providing "message of the day" functionality.
  version: "1.0.0"
  contact:
    email: hollygrahamplank@gmail.com
    url: hollyplank.com
    name: Holly Plank
  license:
    name: BOBBO-NET Friendly MIT License
    url: https://github.com/HollyGrahamPlank/motd-api-ts/blob/main/LICENSE.md
  title: "MOTD API"
paths:
  /:
    get:
      summary: Get latest MOTD
      description: Retrieves the latest message of the day.
      responses:
        "200":
          description: The latest MOTD.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MOTD"
        "404":
          description: There are no MOTDs.
    post:
      summary: Create new MOTD
      description: Creates a new MOTD and returns information about it.
      requestBody:
        description: Data for the new MOTD.
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - message
              properties:
                message:
                  $ref: "#/components/schemas/MOTD/properties/message"
      responses:
        "200":
          description: Information about the newly created MOTD.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MOTD"
        "415":
          description: Incorrect Content-Type.
        "400":
          description: Invalid arguments. Message must not be empty.
  /{id}:
    get:
      summary: Get specific MOTD
      description: Retrieves a specific message of the day.
      parameters:
        - in: path
          name: id
          description: The ID of the MOTD to get.
          required: true
          schema:
            type: string
            format: mongo-objectid
            example: fMW0PcHRJGUtUnadq4mvy
      responses:
        "200":
          description: The MOTD with the matching ID.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MOTD"
        "400":
          description: Malformatted ID provided.
        "404":
          description: No MOTD by that ID found.
    patch:
      summary: Update specific MOTD
      description: Updates the message field of a specific message of the day.
      parameters:
        - in: path
          name: id
          description: The ID of the MOTD to update.
          required: true
          schema:
            type: string
            format: mongo-objectid
            example: fMW0PcHRJGUtUnadq4mvy
      requestBody:
        description: Fields of the MOTD to update.
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  $ref: "#/components/schemas/MOTD/properties/message"
      responses:
        "200":
          description: The updated MOTD.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MOTD"
        "400":
          description: Malformatted ID provided.
        "404":
          description: No MOTD by that ID found.
        "415":
          description: Incorrect Content-Type.
    delete:
      summary: Remove specific MOTD
      description: Removes a specific message of the day.
      parameters:
        - in: path
          name: id
          description: The ID of the MOTD to remove.
          required: true
          schema:
            type: string
            format: mongo-objectid
            example: fMW0PcHRJGUtUnadq4mvy
      responses:
        "200":
          description: The MOTD with the matching ID was removed.
        "400":
          description: Malformatted ID provided.
        "404":
          description: No MOTD by that ID found.
  /history:
    get:
      summary: Get previous MOTDs
      description: Get a list of previous message of the days, sorted by newest to oldest. Results are paginated.
      parameters:
        - in: query
          name: previousLastId
          description: If paginating, the value of the `lastId` from the previous request.
          required: false
          schema:
            type: string
            format: mongo-objectid
            example: fMW0PcHRJGUtUnadq4mvy
        - in: query
          name: pageSize
          description: If paginating, the max number of entries per-page.
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 32
            default: 8
      responses:
        "200":
          description: A list of MOTDs (after `previousLastId`, if provided)
          content:
            application/json:
              schema:
                type: object
                properties:
                  lastId:
                    type: string
                    format: mongo-objectid
                    example: fMW0PcHRJGUtUnadq4mvy
                  items:
                    type: array
                    items:
                      $ref: "#/components/schemas/MOTD"
        "400":
          description: Malformed `previousLastId` or `pageSize`.

components:
  schemas:
    MOTD:
      description: An object representing some message of the day.
      type: object
      required:
        - _id
        - message
        - createdAt
        - updatedAt
      properties:
        _id:
          description: The ID representing this MOTD.
          type: string
          format: mongo-objectid
          example: fMW0PcHRJGUtUnadq4mvy
        message:
          description: The message text contained in this MOTD.
          type: string
          example: "You know what they say: a watched pot never stops!"
        createdAt:
          description: The date & time that this MOTD was originally created at.
          type: string
          format: date-time
        updatedAt:
          description: The date & time that this MOTD was last updated at.
          type: string
          format: date-time

servers:
  - url: http://localhost:30330
    description: The local express deployment
