services:
  # The Express server
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
      DB_URL: mongodb://database:27017
    ports:
      - 3000:3000
    depends_on:
      - database
    networks:
      - node-network

  # The MongoDB database
  database:
    image: mongo:6-jammy
    ports:
      - "27017:27017"
    volumes:
      - dbdata6:/data/db
    networks:
      - node-network

volumes:
  dbdata6:

networks:
  node-network:
    driver: bridge
